@baseURL = http://localhost:3001

@contentType = application/json


# Log in an account
POST {{baseURL}}/auth/log-in
Content-Type: {{contentType}}

{
    "email": "sogolo@gmail.com",
    "password": "sha256"
}